FILENAME: $PLUGIN_ID$-v$VERSION$.mcdr
EXPORT_DIRECTORY: plugin

INCLUDE:
  DIRECTORY:
    - $PLUGIN_ID$
    - lang
  FILE:
    - mcdreforged.plugin.json

EXCLUDE:
  DIRECTORY: []
  FILE: []